Split codebase into separate files
timeshifter/twitch-filtered-chat pull request #6
Opened 2018-11-17 14:33 UTC by fnky

This PR splits the codebase into separate files in order to improve readability and maintainability.

- Scripts are defined within `main.js`.
- CSS are defined in `styles.css`
- HTML is declared within `index.html`

This also introduces additional changes:

- Properly declare the HTML5 document.
- Prettified codebase—using [prettier](https://prettier.io/)
- HTML escape implementation from #5

Closes #4

2018-11-17 21:07 UTC, AhiVT requested changes
Great work! This is exactly what this project needed! ~~There are just some 'linting' things that need to be done to bring it to spec. Specifically, I noticed that in your HTML tags you put the `>` character on a new line. This may be confusing to contributors and should be placed on the same line as the declared tag. Eg: `<label` and `</label` should be declared as `<label>` and `</label>` respectively. You can find an example of these linting issues on lines 165 - 167 and 179 - 185 to name a few. I've also noticed that your CSS is improperly formatted causing the site layout to not render correctly. In CSS, rules must be specified on **one line**. Eg. Line 1 in your `styles.css` should read `*, *:before, *:after {`~~
**I stand corrected, please see my next comment**

2018-11-17 22:19 UTC, Kexerval commented
I noticed when I ran a local copy of your PR to fix the CSS formatting the site remained broken after I fixed the CSS rule. **I've pinpointed the issue to the change from XHTML to HTML5.**
### Here's why that is:
When browsers like Chrome read a HTML without `<!DOCTYPE html>` or they are written in XHTML the browser will render the page in quirk-mode. Quirks mode changes the fundamental properties of how CSS works with the DOM. Since this site was written using Quirks Mode, the CSS rules worked around these Quirks. A list of CSS differences in Quirk Mode can be found [here](https://developer.mozilla.org/en-US/docs/Mozilla/Mozilla_quirks_mode_behavior)

**TL; DR: Quirk-mode must be enabled to properly render the site. I've created a PR with this change for you @fnky **

2018-11-18 23:54 UTC, fnky commented
Hey @Kexerval thanks for the review.

The reason for the `>` on a second line is due to prettier accommodating for sensitive whitespacing in HTML as well as keeping everything within 80 characters as much as possible.

You can read more about how [HTML whitespace sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) works in Prettier.

Regarding the quirks mode, I had a look and it seemed that the `#wrapper` selector didn't have a proper height to make everything full-height. This has been fixed.

I don't quite know what you mean by converting to CSS 3.0 standards; I tried to validate the CSS in the [CSS Validation Service](https://jigsaw.w3.org/css-validator) and everything seemed fine.

I also validated the HTML using the [Markup Validation Service](https://validator.w3.org) and after adding the missing `alt` attribute to an image, it is also passing.

2018-11-19 00:20 UTC, fnky commented
I sorted out the HTML wrapping for the tags by exceeding the line width limit to 120.

2018-11-19 01:06 UTC, Kexerval commented
Regarding "Standards CSS," this basically means that no special rulesets (Such as the Quirks Ruleset `layout/style/quirk.css`) will be applied by the browser renderer. I was able to verify that the CSS written for the site relied on a Quirks Ruleset to the DOM by removing `<!DOCTYPE html>` from line 1 in commit [8a8d402](https://github.com/timeshifter/twitch-filtered-chat/blob/8a8d402b0eb25b73295853ad6917baf3eed3977a/index.html). This rendered the page correctly without any additional CSS changes. Even so, the Quirks Ruleset should only be used for webpages made using older HTML versions. 

But there's great news! You've made the changes needed to resolve #7 in commit [82c440d](https://github.com/timeshifter/twitch-filtered-chat/pull/6/commits/82c440d0569793e25806cdb95955c9532069f392) so we don't have to worry about Quirks Mode any longer.

Thank you for taking the time to explain Prettier!

2018-11-19 01:07 UTC, AhiVT approved these changes
Webpage renders correctly from HEAD!

2018-11-28 02:28 UTC, AhiVT commented
@timeshifter Bumping for your review

2018-12-04 18:12 UTC, Chris-Johnston requested changes
I like the idea of using a pre-commit hook to prettify the CSS. I think it may be helpful to include instructions on how to Prettier manually in the Readme, as well.

2018-12-04 18:12 UTC, Chris-Johnston commented on main.js
> +
Missing chat message filtering from 985d77439aa0f5c4e8861a05a963024b27ec20c8
```suggestion
  message = message.replace(/</g, '&lt;').replace(/>/g, '&gt');
```

2018-12-06 03:12 UTC, Kexerval commented on main.js
> +
Does this change reside within the if statement on line 396 or outside of it? Unclear from suggested change overview.

2018-12-06 04:40 UTC, Chris-Johnston commented on main.js
> +
Just outside it. Now that you mention it, I need to fix the indentation on that line, so I'll do that now.

2018-12-08 22:05 UTC, Kexerval commented
@fnky timeshifter has merged #5 which makes this PR conflict. Any chance to resolve? Thanks!

2018-12-20 17:52 UTC, fnky commented
I had to force push changes due to some incompatibilities between commits.

This branch already introduced the same escape function, although only slightly different in terms of naming.

It is now up-to-date with `master`.

2019-02-20 22:29 UTC, closed without merging